apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
        - name: my-express-app
          image: gcr.io/finaltask-387817/my-express-app
          ports:
            - containerPort: 8080
